### ISSUE TITLE
[rind]'s small idiosyncrasy

### ISSUE THREAD

**Issue by gilbertohasnofb** [myQwil/pd-externals#4]
On my Linux machine, **[rind]** has a small idiosyncrasy which is a bit annoying: if both max and min limits are set to be the same value (both via the inlets or arguments), the output is _not_ the expected. For instance, if both min and max are set to `5.7`, then the result should be `5.7`, not another value. The solution is to force the max value to be slightly larger, in the example above `5.7001` for instance.

One of the practical cases in which this situation appear is when both max and min limits slowly diver from a single value (e.g. using **[line]**).

**Comment by myQwil** [comment]
Interesting. Let me look into that, there should be an easy enough fix.

**Comment by myQwil** [comment]
Basically, it happens because when the range equals 0, it defaults to 1, but I'll change it so that's only checked upon creation of the object, and only when no arguments are specified

**Comment by myQwil** [comment]
It should be working now. I've created a linux binary

**Comment by gilbertohasnofb** [comment]
Confirmed, thanks for the quick fix.
